export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FAVOURITE_LOADING = "LOADING";
export const FAVOURITE_SUCCESS = "FAVOURITE_SUCCESS";
export const FAVOURITE_FAIL = "FAVOURITE_FAIL";

export const SHIRTS_LOADING = "SHIRTS_LOADING";
export const SHIRTS_SUCCESS = "SHIRTS_SUCCESS";
export const SHIRTS_FAIL = "SHIRTS_FAIL";

export const SHIRT_LOADING = "SHIRT_LOADING";
export const SHIRT_SUCCESS = "SHIRT_SUCCESS";
export const SHIRT_FAIL = "SHIRT_FAIL";

export const ADD_LOADING = 'ADD_LOADING';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const ADD_FAIL = 'ADD_FAIL';
